# Generated by Django 2.2.8 on 2019-12-08 04:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_override', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gallery.Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order'],
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('gallery_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery_thumbnails')),
                ('locked', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='gallery.Category')),
            ],
            options={
                'verbose_name_plural': 'Galleries',
                'ordering': ['sort_order'],
                'verbose_name': 'Gallery',
            },
        ),
    ]
