# Generated by Django 2.2.5 on 2019-12-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Model creation time.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time.')),
                ('name', models.CharField(editable=False, help_text="User's name.", max_length=100)),
                ('email', models.EmailField(editable=False, help_text="User's email.", max_length=254)),
                ('message', models.TextField(editable=False, help_text="User's message.", max_length=2047)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
