# Generated by Django 2.2.5 on 2019-12-18 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='category',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Whether the category should be hidden from the navbar.'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Whether the gallery should be hidden from the category view.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='link_override',
            field=models.CharField(blank=True, default=None, help_text='A link which overrieds the category url in the navbar.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Name of the category.', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='A parent category seen as the dropdown link on navbar.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gallery.Category'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(help_text='Category in which the gallery resides.', on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='gallery.Category'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='locked',
            field=models.BooleanField(default=True, help_text='Whether the images within the gallery can be downloaded or are free from watermark.'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='The thumbnail of the gallery which may be left blank.', null=True, upload_to='gallery_thumbnails'),
        ),
    ]
