# Generated by Django 2.2.5 on 2019-11-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20191108_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='link_override',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
