# Generated by Django 2.2.5 on 2019-11-09 10:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20191108_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('gallery_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='gallery.Category')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'ordering': ['sort_order'],
            },
        ),
    ]
