# Generated by Django 2.2.5 on 2019-12-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20191218_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='random_thumbnail',
            field=models.BooleanField(default=True, help_text="Whether a random thumbnail should be picked if the thumbnail isn't set."),
        ),
    ]
