# Generated by Django 2.2.5 on 2019-11-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_thumbnails'),
        ),
    ]
