# Generated by Django 2.2.5 on 2019-12-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_gallery_random_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_all', models.BooleanField(default=False, help_text='Lock all galleries.')),
                ('disable_creation', models.BooleanField(default=False, help_text='Disable creation of thumbnails or watermarks.')),
            ],
        ),
    ]
