# Generated by Django 2.2.5 on 2019-12-19 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
    ]
