# Generated by Django 2.2.5 on 2019-12-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_category_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='banner',
            field=models.CharField(blank=True, default=None, help_text="A banner shown on the Category's page.", max_length=1000, null=True),
        ),
    ]
