# Generated by Django 2.2.5 on 2019-12-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20191220_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='use_x_sendfile',
            field=models.BooleanField(default=True, help_text="Whether to send files using Nginx's XSendFile Header or not."),
        ),
    ]
