# Generated by Django 2.2.5 on 2019-12-23 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_settings_use_x_sendfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['sort_order'], 'verbose_name': 'Gallery', 'verbose_name_plural': 'Menus'},
        ),
    ]
