# Generated by Django 2.2.5 on 2019-12-23 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_auto_20191222_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order'], 'verbose_name': 'Category', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['sort_order'], 'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
    ]
