# Generated by Django 2.2.5 on 2019-12-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20191222_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='disable_creation',
        ),
    ]
