# Generated by Django 3.0.2 on 2020-01-31 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_remove_settings_disable_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('number', models.PositiveSmallIntegerField()),
                ('order_photos', models.BooleanField()),
                ('order_videos', models.BooleanField()),
                ('heats', models.CharField(blank=True, max_length=254, null=True)),
                ('event_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='gallery.Category')),
            ],
        ),
    ]
