# Generated by Django 3.0.2 on 2020-01-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('U', 'Unpaid'), ('C', 'Cash'), ('S', 'Square (Card)'), ('E', 'E-Transfer')], default='U', max_length=1),
        ),
    ]
