# Generated by Django 3.0.2 on 2020-01-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_auto_20200131_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
