# Generated by Django 3.0.2 on 2020-01-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_auto_20200131_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Dancer Number'),
        ),
    ]
